### ISSUE TITLE
Неполный enum TradeStatus в swagger

### ISSUE THREAD

**Issue by finico** [TinkoffCreditSystems/invest-openapi#80]
Сейчас TradeStatus такой

```yaml
TradeStatus:
      type: string
      enum:
        - NormalTrading
        - NotAvailableForTrading
```

Сегодня от stream api пришел статус `break_in_trading`
Хорошо бы добавить
